name: CI

on:
  push:
    branches:
      - master
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "release-*"
  pull_request:
    branches:
      - master
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "release-*"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm clean-install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test -- --coverage --watchAll=false

